version: 2
ethernets:
  nic0:
    match:
      macaddress: "${mac_address}"
    addresses:
      - ${ip_address}/24
    routes:
      - to: default
        via: ${gateway}
    nameservers:
      addresses:
        - 8.8.8.8
        - 8.8.4.4
